### ISSUE TITLE
Ошибка счётчика

### ISSUE THREAD

**Issue by finagin** [Yahevin/go_home#1]
## Запредельные числа на счётчике
<a href="https://github.com/Yahevin/go_home/assets/11045296/dc93739e-ecd5-4de7-beac-44db169490b6" target="_blank">
<img src="https://github.com/Yahevin/go_home/assets/11045296/dc93739e-ecd5-4de7-beac-44db169490b6" width="50%">
</a>

### localstorage
```json
//drink_notes

[
    {
        "timestamp": 1711464323727,
        "volume": 0.5,
        "strength": 5
    },
    {
        "timestamp": 1711467032622,
        "volume": 0.4,
        "strength": 5
    }
]
```
```json
// selected_level

"d"
```

```json
// current timestamp

1711516083482
```

**Comment by Yahevin** [comment]
Исправлено
